version: "3.7" # version du docker compose 

services: # contient l'ensemble des containeurs nécessaires
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  node:
    build:
      context: ./node 
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=production
    ports:
      - 8081:8081
    volumes:
      - .:/app
    expose:
      - "8081"
    command: "npm start"
        
#   web: # container du server web
#     depends_on:
#       - db # depend de la db, démare le container de db avant le container web 
#     build:
#       context: . # chemin vers Dockerfile (image)
#     volumes:
#       - .:/code # notre appli est dans le dossier courant(.) mais pour le container docker il sera dans le dossier code
#     ports:
#       - 8000:8000
#     command: [ "symfony", "server:start" ]

# volumes: # déclaration du volume pour la persistance 
#   db:
#     name: db



